исправлен блок output
js-tasks-ru/vue-20231109_pechatnova-n pull request #4
Opened 2023-11-16 06:56 UTC by pechatnova-n

2023-11-16 06:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-16 08:36 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-16 08:42 UTC, pechatnova-n commented
исправлен блок output в задаче VueCalculator
решение задачи MarkedList

2023-11-16 08:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-11-16 23:34 UTC, ShGKme requested changes

2023-11-16 23:34 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          <li :class="email.flag === 'marked' ? 'marked' : ''">
Во Vue, когда требуется добавить класс по условию, принято использовать синтаксис привязки класса объектом. Объект явно описывает, какой класс по какому выражению требуется добавлять.

https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects 

Так явно видно, от чего зависит наличие каждого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы. 

И не требуется делать `else` с пустой строкой в тернарном операторе.

2023-11-16 23:34 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  }
`getNewEmailsArray` - это вычисляемое свойство. Ни в коем случае нельзя мутировать значение вычисляемого свойства, оно только для чтения.

Это значение может в любой момент времени быть перезаписано, если Vue заново вычислит значение вычисляемого свойства.

2023-11-16 23:34 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +   },
Сейчас это свойство описывает массив, где `flag` всегда пустая строка `''`.

2023-11-16 23:34 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  }
Например, если изменится список `email`-ов

2023-11-17 08:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-17 21:11 UTC, ShGKme reviewed
Исправления приняты

2023-11-17 21:21 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-17 21:35 UTC, ShGKme approved these changes
Принято

2023-11-17 21:35 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
> +<html lang="ru" xmlns="http://www.w3.org/1999/html">
Начиная с HTML 5 (2012) этот атрибут больше не нужен и устаревший.

2023-11-17 21:35 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
> +          :value="index+1"/>{{ item }}</label>
Vue в циклах по числу начинает отсчёт с 1, увеличивать на 1 не нужно, иначе здесь выводится от 2 до 6.

2023-11-17 21:35 UTC, merged