02-components
js-tasks-ru/vue-20231109_pechatnova-n pull request #5
Opened 2023-11-24 11:02 UTC by pechatnova-n

2023-11-24 11:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-24 20:17 UTC, ShGKme requested changes

2023-11-24 20:17 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +    },
Это не приводит к ошибкам, но переопределять значение аргументов функции считается плохой практикой.
Подробнее: https://spin.atomicobject.com/2011/04/10/javascript-don-t-reassign-your-function-arguments/

И в этой функции это изменение даже не используется, значение `count` после увеличения нигде не используется в методе.

Для возврата значения на 1 больше его не требуется увеличивать.

2023-11-24 20:17 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +  },
Эти объекты не являются данными компонента, они не определяют его реактивное состояние

2023-11-24 20:17 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +      }
`error` - это экземпляр класса Error в JS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

Его сообщение можно получить из свойства `message`

2023-11-24 20:17 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
> +  },
Код в `mounted` и в `watch` - идентичный. Лучше его не дублировать, а хотя бы вынести в метод.

2023-11-24 20:17 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
>        </UiContainer>
Этот контейнер выводится всегда, даже если ошибки нет (так как условие только на содержимом контейнера).

2023-11-24 20:17 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
>        </UiContainer>
Здесь всегда выводится или митап, или индикатор загрузки. Даже если загрузка завершилась, а митапа нет из-за ошибки.

2023-11-25 10:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-26 14:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-27 15:35 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-27 22:43 UTC, ShGKme requested changes

2023-11-27 22:43 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button @click=this.$emit('update:count',++this.count); type="button">{{ count }}</button>`,
Здесь происходит мутация входного параметра `count`. Входные параметры только для чтения, их нельзя изменять. Во время работы компонента в консоли выводятся ошибки. Для передачи в аргумент функции значения на 1 больше, чем в переменной, саму переменную не требуется изменять. Достаточно вычислить значение на 1 больше.

2023-11-27 22:43 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button @click=this.$emit('update:count',++this.count); type="button">{{ count }}</button>`,
Также в шаблоне не используют `this`, так как он уже выполняется в области видимости свойств экземпляра компонента.

2023-11-27 22:43 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button @click=this.$emit('update:count',++this.count); type="button">{{ count }}</button>`,
А значение директивы, как и значение любых атрибутов, всегда пишут в кавычках. Иначе здесь даже не поставить пробел после запятой — теряется граница значения.

2023-11-28 07:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-28 10:20 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-28 18:52 UTC, ShGKme approved these changes
Все задачи приняты

2023-11-28 18:52 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
Параметр не может быть одновременно `required` и иметь `default`. Первое означает, что параметр передавать обязательно, а второй - как компоненту действовать если параметр не передали.

2023-11-28 18:54 UTC, merged