tasks
js-tasks-ru/vue-20231109_pechatnova-n pull request #6
Opened 2023-12-08 11:32 UTC by pechatnova-n

2023-12-08 11:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-08 12:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-08 12:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-10 15:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-10 16:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-10 16:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-11 16:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-14 09:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-14 09:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-14 10:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-14 12:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-15 16:14 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-20 19:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-22 00:28 UTC, ShGKme requested changes
В `03-sfc/02-UiTransitionGroupFade` не совсем корректно работают стили

В `04-vue-cli/02-TheToaster` новый компонент получился не самостоятельным, работающим только в конкретном месте при определённом использовании.

В `04-vue-cli/04-MeetupsCalendar` у вычисляемого свойства есть побочный эффект.

---

Остальные задачи приняты.

2023-12-22 00:28 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +             :class="[ {'button_block': block}, { [createClassName]: variant} ]"
`variant` всегда есть, потому второй объект `{ [createClassName]: variant}` можно заменить на `createClassName`.

2023-12-22 00:28 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +  <component :is="tag || 'router-link'" class="link">
Значение по умолчанию должно быть задано в описании входного параметра.

2023-12-22 00:28 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +:deep(.fade-list)  {
Изменение стиля здесь поменяло и селектор. Раньше этот стиль действовал на дочерние элементы от `.fade-list` (`> *`), а сейчас действует на сам `.fade-list`. При этом из-за `deep` он действует не только на `.fade-list` этого компонента (а этот элемент выводится самим компонентом, то есть стиль на `.fade-list` работает изначально), но вообще на все элементы с классами `.fade-list` на странице.

2023-12-22 00:28 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +.fade-list:deep(.fade-list-move) {
Не влияет на работу, но лучше здесь оставить пробел, чтобы было явно видно, что это селектор на потомство, а не на мультикласс.

2023-12-22 00:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +        id: Date.now(),
Лучше не использовать `Date.now()` в качестве идентификатора. Он не гарантирует уникальность. Два вместе добавленных тоста могут быть добавлены за 1мс.

Вместо этого можно использовать случайные значения или авто-инкремент.

2023-12-22 00:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  <div :class="[{ 'toast_success' : toastType === 'success' }, { 'toast_error' : toastType === 'error' }]">
Множество классов по условию можно описывать свойствами одного объекта, не разделяя на массив объектов с одним свойством. Но в случае этого компонента проще вычислить имя класса явно как `toast_${toastType}`. Мы сами контролируем, какие классы у этого компонента и какие значения параметров, и можем для себя гарантировать, что класс можно вычислить из стиля.

2023-12-22 00:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    <UiIcon v-if="toastType === 'error'" class="toast__icon" icon="alert-circle" />
Когда по условию меняется лишь содержимое узла или значение параметра/атрибута, лучше в шаблоне определять условием именно изменяющееся значение.

С `v-if` получается копирование целиком узла, это дублирование всего кода узла с остальными его атрибутами.

2023-12-22 00:28 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</style>
Этот компонент нельзя использовать как самостоятельный компонент. Всего стили и даже один из классов, необходимых для его отображения, описаны в компоненте `TheToaster`. В результате компонент получается очень не переиспользуемые, работающий только в одном месте.

2023-12-22 00:28 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Вычисляемое свойства - это именно свойства. Для них описывается функция, с помощью которой Vue будет вычислять значение вычисляемого свойства, но оно остаётся свойством. По этой причине вычисляемые свойства обычно называют, как свойства, а не как функции (не с глагола, без get).

2023-12-22 00:28 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    }
Это вычисляемое свойство в процессе своей работы не только вычисляет массив дней, но и имеет побочные эффекты - изменяет состояние компонента.

Вычисляемые свойства должны только вычислять значение и ни в коем случае не иметь побочных эффектов вычисления.

2023-12-22 00:28 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +          <a v-for="meetup in filterMeetups(day['date'])" :key="meetup.id" :href="`/meetups/${meetup.id}`"
Сейчас во время рендеринга вызывается метод. Вызывать метод в шаблоне в целом обычно не лучшая практика. Это делает шаблон не декларативным, и требует дополнительно проверять, что метод не имеет побочных эффектов и производительный. Иногда это допустимо, когда метод используется для форматирования вывода или немного упрощает код в компоненте.

Но метод `filterMeetups` здесь используется для описания логики работы с данными - формирует массив данных для вывода прямо во время рендеринга. Это уже перетекание логики обработки данных в шаблон, при этом неоптимальное.

В итоге сейчас при рендеринге каждой ячейки календаря происходит перебор всех-всех митапов для проверки, а не попадает ли этот митап в эту ячейку. Потом ещё раз для следующей ячейки. И так для всех дней месяца. И всё это повторяется при каждом ре-рендеринге компонента, даже если результат не изменится.

Вместо этого лучше готовить данные для их удобного вывода без дополнительных перевычислений.

---

Это можно будет сделать во второй итерации работы с календарём в задаче будущей темы.

2023-12-22 09:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-22 12:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-24 16:18 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-24 18:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-24 18:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-24 20:56 UTC, ShGKme requested changes
Осталась одна проблема из старых - в `04-vue-cli/04-MeetupsCalendar` у вычисляемого свойства есть побочный эффект.

Остальные задачи приняты.

2023-12-24 20:56 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +  },
Это свойство не используется компонентом

2023-12-24 20:56 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +      } else {
К параметрам обычно принято обращаться по короткому пути, без `$props`

2023-12-24 20:56 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +      } else {
Лучше не оставлять лог, чтобы не засорять общий лог тестирования в задачнике (и приложения в реальной жизни).

2023-12-24 20:56 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +  },
Если константы используются только в `JS` части компонента и не нужны в свойствах экземпляра, в шаблоне - их можно описывать как обычные JS переменные.

2023-12-25 08:38 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-27 22:09 UTC, ShGKme requested changes
Осталась проблема в `04-vue-cli/04-MeetupsCalendar`.

Сейчас во время вычисления значения вычисляемого свойства `getDays` вызывается метод `getInactiveDays`, который изменяет состояние компонента мутируя свойства `startDate` и `endDate`.

Получается побочный эффект вычисления вычисляемого свойства. Он не только вычисляет само свойство, но и два других свойства компонента.

Чтобы этого избежать в текущей реализации достаточно просто убрать вообще эти свойства. Их значение никогад не используется.

2023-12-28 13:27 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-28 18:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-12-28 19:01 UTC, ShGKme approved these changes

2023-12-28 19:05 UTC, merged