tasks solution
js-tasks-ru/vue-20231109_pechatnova-n pull request #7
Opened 2024-01-11 12:57 UTC by pechatnova-n

2024-01-11 12:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-12 10:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-14 09:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-14 13:16 UTC, ShGKme reviewed
Все решённые в этом PR задачи приняты.

2024-01-14 13:16 UTC, ShGKme commented on 12-provide-inject/01-UiButtonGroup-provide/components/UiButtonGroup.vue
> +  },
Так как `provide/inject` не ограничивается только этими двумя компонентами, лучше называть ключи так, чтобы было понятно, что это за сущности, откуда/для чего они, и так чтобы они не пересекались случайно с другими компонентами.

2024-01-14 15:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-14 16:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-18 17:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-18 18:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-18 18:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-18 18:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-22 23:03 UTC, ShGKme requested changes

2024-01-22 23:03 UTC, ShGKme commented on 08-reactivity/04-debouncedRef/utils/debouncedRef.js
> +  watch(() => source.value, update);
Так как `source` - реактивный, то можно следить сразу за ним `watch(source, `

2024-01-22 23:03 UTC, ShGKme commented on 10-slots/01-UiPaginationView/components/UiPaginationView.vue
> +      </div>
Оборачивание в див здесь лишнее. Слот можно выводить с циклом и без дополнительных узлов, а вот наличие дива может мешать делать корректную и валидную вёрстку.

2024-01-22 23:03 UTC, ShGKme commented on 08-reactivity/02-scroll-after-update/components/MiniMessenger.vue
> +  }
Делать источником скроллинга изменение длины списка не совсем корректно. Это означает, например, что прокручиваться список будет и при добавлении новых сообщений в истории сообщений, и при удалении любого сообщения из середины.

Хотя часто для нас в Vue источником действия является изменение данных, здесь тот случай, когда более корректным инициатором скроллинга в конце делать именно факт отправки сообщения, то есть непосредственно в методе отправки.

Кроме того, хотя `flush: 'post',` здесь полностью рабочее решение, на практике в 99.9% случаев используется `nextTick` и лучше работать через него (большинство разработчиков вообще не знают про `flush`)

2024-01-23 07:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-23 16:14 UTC, ShGKme submitted a review, later dismissed
Исправления приняты

2024-01-23 16:14 UTC, jsru commented
К сожалению, PR не может быть замержен, ShGKme вероятно сможет помочь.

2024-01-23 16:15 UTC, ShGKme reviewed
Исправления приняты

2024-01-24 07:56 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-01-24 07:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-01-30 23:44 UTC, ShGKme approved these changes

2024-01-30 23:44 UTC, ShGKme commented on 08-reactivity/02-scroll-after-update/components/MiniMessenger.vue
>        await nextTick();
Здесь получилось два `nextTick()`-а после соединения вашего решения и авторского.

2024-01-30 23:45 UTC, merged